export { isValid } from "./isValid";
export { isNIE } from "./isNIE";
export { isNIF } from "./isNIF";
export { randomNIF } from "./randomNIF";
export { randomNIE } from "./randomNIE";
export { ctrlChar } from "./ctrlChar";
export { randomNIFWith } from "./randomNIFWith";
export { randomNIEWith } from "./randomNIEWith";
export { normalize } from "./normalize";
