name: Node.js CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/better-dni

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn run build
      - run: yarn test
      - uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ${{ github.workspace }}/packages/better-dni/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
